//! Vector store for entity embeddings via Qdrant HTTP API.
//!
//! Stores and queries embeddings generated by the ontology constructor.
//! Uses Qdrant's REST API — no gRPC dependency needed.

use std::hash::{Hash, Hasher};

use anyhow::{bail, Context, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tracing;
use uuid::Uuid;

use crate::{EmbeddingBatch, QdrantConfig};

/// Trait for vector storage backends.
#[async_trait]
pub trait VectorStore: Send + Sync {
    /// Store a batch of embeddings. Returns count of vectors stored.
    async fn upsert(&self, batch: &EmbeddingBatch) -> Result<usize>;

    /// Query for the `k` nearest neighbors of a vector.
    /// Returns (id, score) pairs sorted by descending similarity.
    async fn query(&self, vector: &[f32], k: usize) -> Result<Vec<(String, f32)>>;

    /// Delete vectors by IDs.
    async fn delete(&self, ids: &[String]) -> Result<usize>;

    /// Count total vectors in the collection.
    async fn count(&self) -> Result<usize>;
}

/// Qdrant-backed vector store.
pub struct QdrantVectorStore {
    client: reqwest::Client,
    config: QdrantConfig,
}

// -- Qdrant API types --

#[derive(Serialize)]
struct UpsertRequest {
    points: Vec<PointStruct>,
}

#[derive(Serialize)]
struct PointStruct {
    id: String,
    vector: Vec<f32>,
    payload: serde_json::Value,
}

#[derive(Serialize)]
struct SearchRequest {
    vector: Vec<f32>,
    limit: usize,
    with_payload: bool,
}

#[derive(Deserialize)]
struct SearchResponse {
    result: Vec<ScoredPoint>,
}

#[derive(Deserialize)]
struct ScoredPoint {
    id: PointId,
    score: f32,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum PointId {
    Str(String),
    Num(u64),
}

impl PointId {
    fn to_string_id(&self) -> String {
        match self {
            PointId::Str(s) => s.clone(),
            PointId::Num(n) => n.to_string(),
        }
    }
}

#[derive(Serialize)]
struct DeleteRequest {
    points: Vec<String>,
}

#[derive(Deserialize)]
struct CollectionInfoResponse {
    result: CollectionInfo,
}

#[derive(Deserialize)]
struct CollectionInfo {
    points_count: Option<usize>,
    vectors_count: Option<usize>,
}

#[derive(Serialize)]
struct CreateCollectionRequest {
    vectors: VectorParams,
}

#[derive(Serialize)]
struct VectorParams {
    size: usize,
    distance: String,
}

// QdrantStatus removed — not needed for current health check implementation.

/// Generate a deterministic UUID from a string name (no v5 feature needed).
fn deterministic_uuid(name: &str) -> String {
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    name.hash(&mut hasher);
    let hash = hasher.finish();
    // Build a UUID-like string from the hash.
    let bytes = hash.to_le_bytes();
    let mut uuid_bytes = [0u8; 16];
    uuid_bytes[..8].copy_from_slice(&bytes);
    // Mirror to fill 16 bytes with a different seed.
    let mut hasher2 = std::collections::hash_map::DefaultHasher::new();
    format!("prism:{name}").hash(&mut hasher2);
    let hash2 = hasher2.finish();
    uuid_bytes[8..].copy_from_slice(&hash2.to_le_bytes());
    // Set version 4 + variant bits for valid UUID format.
    uuid_bytes[6] = (uuid_bytes[6] & 0x0f) | 0x40;
    uuid_bytes[8] = (uuid_bytes[8] & 0x3f) | 0x80;
    Uuid::from_bytes(uuid_bytes).to_string()
}

impl QdrantVectorStore {
    pub fn new(config: QdrantConfig) -> Self {
        let mut builder = reqwest::Client::builder();
        if let Some(ref key) = config.api_key {
            let mut headers = reqwest::header::HeaderMap::new();
            headers.insert(
                "api-key",
                reqwest::header::HeaderValue::from_str(key).expect("invalid API key"),
            );
            builder = builder.default_headers(headers);
        }
        let client = builder.build().expect("failed to build HTTP client");
        Self { client, config }
    }

    /// Base URL for collection operations.
    fn collection_url(&self) -> String {
        format!(
            "{}/collections/{}",
            self.config.base_url, self.config.collection
        )
    }

    /// Check Qdrant connectivity.
    pub async fn health_check(&self) -> Result<()> {
        let url = format!("{}/healthz", self.config.base_url);
        let resp = self
            .client
            .get(&url)
            .send()
            .await
            .context("Qdrant not reachable")?;

        if !resp.status().is_success() {
            bail!("Qdrant health check failed: {}", resp.status());
        }
        Ok(())
    }

    /// Ensure the collection exists, creating it if needed.
    pub async fn ensure_collection(&self, dimension: usize) -> Result<()> {
        let url = self.collection_url();
        let resp = self.client.get(&url).send().await;

        match resp {
            Ok(r) if r.status().is_success() => {
                tracing::debug!(collection = %self.config.collection, "collection exists");
                Ok(())
            }
            _ => {
                tracing::info!(
                    collection = %self.config.collection,
                    dimension,
                    "creating Qdrant collection"
                );
                let body = CreateCollectionRequest {
                    vectors: VectorParams {
                        size: dimension,
                        distance: "Cosine".into(),
                    },
                };
                let create_resp = self
                    .client
                    .put(&url)
                    .json(&body)
                    .send()
                    .await
                    .context("failed to create Qdrant collection")?;

                if !create_resp.status().is_success() {
                    let text = create_resp.text().await.unwrap_or_default();
                    bail!("failed to create collection: {text}");
                }
                Ok(())
            }
        }
    }
}

#[async_trait]
impl VectorStore for QdrantVectorStore {
    async fn upsert(&self, batch: &EmbeddingBatch) -> Result<usize> {
        if batch.vectors.is_empty() {
            return Ok(0);
        }

        // Auto-create collection if we know the dimension.
        if let Some(dim) = batch.dimension {
            self.ensure_collection(dim).await?;
        } else if let Some(first) = batch.vectors.first() {
            self.ensure_collection(first.len()).await?;
        }

        let points: Vec<PointStruct> = batch
            .vectors
            .iter()
            .zip(batch.ids.iter())
            .map(|(vec, id)| {
                // Qdrant requires UUID or integer IDs. Use the id as-is if it
                // looks like a UUID, otherwise generate a deterministic UUID v5.
                let point_id = if Uuid::parse_str(id).is_ok() {
                    id.clone()
                } else {
                    deterministic_uuid(id)
                };

                PointStruct {
                    id: point_id,
                    vector: vec.clone(),
                    payload: serde_json::json!({ "name": id }),
                }
            })
            .collect();

        let count = points.len();
        let url = format!("{}/points?wait=true", self.collection_url());
        let body = UpsertRequest { points };

        let resp = self
            .client
            .put(&url)
            .json(&body)
            .send()
            .await
            .context("failed to upsert vectors to Qdrant")?;

        if !resp.status().is_success() {
            let text = resp.text().await.unwrap_or_default();
            bail!("Qdrant upsert failed: {text}");
        }

        tracing::info!(count, collection = %self.config.collection, "vectors upserted");
        Ok(count)
    }

    async fn query(&self, vector: &[f32], k: usize) -> Result<Vec<(String, f32)>> {
        let url = format!("{}/points/search", self.collection_url());
        let body = SearchRequest {
            vector: vector.to_vec(),
            limit: k,
            with_payload: true,
        };

        let resp = self
            .client
            .post(&url)
            .json(&body)
            .send()
            .await
            .context("Qdrant search failed")?;

        if !resp.status().is_success() {
            let text = resp.text().await.unwrap_or_default();
            bail!("Qdrant search failed: {text}");
        }

        let search: SearchResponse = resp.json().await.context("bad Qdrant search response")?;

        let results: Vec<(String, f32)> = search
            .result
            .into_iter()
            .map(|sp| (sp.id.to_string_id(), sp.score))
            .collect();

        tracing::debug!(k, results = results.len(), "vector search complete");
        Ok(results)
    }

    async fn delete(&self, ids: &[String]) -> Result<usize> {
        if ids.is_empty() {
            return Ok(0);
        }

        let point_ids: Vec<String> = ids
            .iter()
            .map(|id| {
                if Uuid::parse_str(id).is_ok() {
                    id.clone()
                } else {
                    deterministic_uuid(id)
                }
            })
            .collect();

        let count = point_ids.len();
        let url = format!("{}/points/delete?wait=true", self.collection_url());
        let body = DeleteRequest { points: point_ids };

        let resp = self
            .client
            .post(&url)
            .json(&body)
            .send()
            .await
            .context("Qdrant delete failed")?;

        if !resp.status().is_success() {
            let text = resp.text().await.unwrap_or_default();
            bail!("Qdrant delete failed: {text}");
        }

        Ok(count)
    }

    async fn count(&self) -> Result<usize> {
        let url = self.collection_url();
        let resp = self
            .client
            .get(&url)
            .send()
            .await
            .context("Qdrant collection info failed")?;

        if !resp.status().is_success() {
            let text = resp.text().await.unwrap_or_default();
            bail!("Qdrant collection info failed: {text}");
        }

        let info: CollectionInfoResponse =
            resp.json().await.context("bad collection info response")?;

        Ok(info.result.points_count.or(info.result.vectors_count).unwrap_or(0))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_qdrant_config() {
        let cfg = QdrantConfig::default();
        assert!(cfg.base_url.contains("6333"));
        assert_eq!(cfg.collection, "prism_embeddings");
        assert!(cfg.api_key.is_none());
    }

    #[test]
    fn point_id_deterministic_for_names() {
        let id1 = deterministic_uuid("Nb25Mo25Ta25W25");
        let id2 = deterministic_uuid("Nb25Mo25Ta25W25");
        assert_eq!(id1, id2);
    }

    #[test]
    fn point_id_different_for_different_names() {
        let id1 = deterministic_uuid("Nb25Mo25Ta25W25");
        let id2 = deterministic_uuid("Ti6Al4V");
        assert_ne!(id1, id2);
    }

    #[test]
    fn collection_url_format() {
        let store = QdrantVectorStore::new(QdrantConfig {
            base_url: "http://localhost:6333".into(),
            collection: "test_coll".into(),
            api_key: None,
        });
        assert_eq!(
            store.collection_url(),
            "http://localhost:6333/collections/test_coll"
        );
    }

    // --- deterministic_uuid edge cases ---

    #[test]
    fn deterministic_uuid_empty_string() {
        // Must not panic and must return a string.
        let id = deterministic_uuid("");
        assert!(!id.is_empty());
    }

    #[test]
    fn deterministic_uuid_valid_uuid_format() {
        let id = deterministic_uuid("some-entity");
        // Must parse as a valid UUID — uuid crate validates format + version/variant bits.
        let parsed = Uuid::parse_str(&id);
        assert!(parsed.is_ok(), "expected valid UUID, got: {id}");
    }

    #[test]
    fn deterministic_uuid_is_deterministic() {
        let id1 = deterministic_uuid("Nb25Mo25Ta25W25");
        let id2 = deterministic_uuid("Nb25Mo25Ta25W25");
        assert_eq!(id1, id2);
    }

    #[test]
    fn deterministic_uuid_with_unicode_input() {
        let id = deterministic_uuid("α-phase BCC");
        let parsed = Uuid::parse_str(&id);
        assert!(parsed.is_ok(), "UUID invalid for unicode input: {id}");
    }

    #[test]
    fn deterministic_uuid_with_very_long_input() {
        let long_name = "X".repeat(10_000);
        let id = deterministic_uuid(&long_name);
        let parsed = Uuid::parse_str(&id);
        assert!(parsed.is_ok(), "UUID invalid for long input: {id}");
    }

    #[test]
    fn deterministic_uuid_different_inputs_produce_different_uuids() {
        let id1 = deterministic_uuid("entity-a");
        let id2 = deterministic_uuid("entity-b");
        assert_ne!(id1, id2);
    }

    // --- collection_url with trailing slash in base_url ---

    #[test]
    fn collection_url_with_trailing_slash_in_base_url() {
        let store = QdrantVectorStore::new(QdrantConfig {
            base_url: "http://localhost:6333/".into(),
            collection: "prism_embeddings".into(),
            api_key: None,
        });
        // The URL will have a double slash — document the current behaviour.
        // This test ensures we're aware of the edge case and it doesn't panic.
        let url = store.collection_url();
        assert!(url.contains("prism_embeddings"));
    }

    // --- QdrantConfig with api_key present ---

    #[test]
    fn qdrant_config_with_api_key_roundtrip() {
        let cfg = QdrantConfig {
            base_url: "https://cloud.qdrant.io".into(),
            collection: "prism".into(),
            api_key: Some("my-secret-key".into()),
        };
        let json = serde_json::to_string(&cfg).unwrap();
        assert!(json.contains("\"api_key\""));
        let parsed: QdrantConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.api_key, Some("my-secret-key".into()));
    }

    // --- QdrantConfig serde skip_serializing_if (api_key=None not in JSON) ---

    #[test]
    fn qdrant_config_api_key_none_omitted_from_json() {
        let cfg = QdrantConfig {
            base_url: "http://localhost:6333".into(),
            collection: "prism_embeddings".into(),
            api_key: None,
        };
        let json = serde_json::to_string(&cfg).unwrap();
        assert!(!json.contains("\"api_key\""),
            "api_key=None should be omitted from JSON, got: {json}");
    }
}
