//! Natural language → Cypher query translation via LLM.
//!
//! Takes a user's natural language question, sends it to any LLM backend
//! (Ollama, OpenAI, MARC27, vLLM) along with the graph schema, and extracts
//! a Cypher query that can be executed against Neo4j.

use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};

use crate::graph::GraphSchemaInfo;
use crate::LlmConfig;

/// Translates natural language queries to Cypher using an LLM.
pub struct NlQueryTranslator {
    client: crate::llm::LlmClient,
}

/// Result of NL→Cypher translation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TranslationResult {
    /// The Cypher query generated by the LLM.
    pub cypher: String,
    /// Brief explanation of what the query does.
    pub explanation: String,
}

impl NlQueryTranslator {
    pub fn new(config: LlmConfig) -> Self {
        let client = crate::llm::LlmClient::new(config);
        Self { client }
    }

    /// Translate a natural language question to a Cypher query.
    pub async fn translate(
        &self,
        question: &str,
        schema: &GraphSchemaInfo,
        limit: usize,
    ) -> Result<TranslationResult> {
        let prompt = build_prompt(question, schema, limit);
        let response = self.client.generate(&prompt).await?;
        parse_response(&response)
    }
}

fn build_prompt(question: &str, schema: &GraphSchemaInfo, limit: usize) -> String {
    let labels = schema.labels.join(", ");
    let rels = schema.relationship_types.join(", ");

    format!(
        r#"You are a Neo4j Cypher query expert for a materials science knowledge graph.

## Graph Schema
Node labels: [{labels}]
Relationship types: [{rels}]

All nodes have a `name` property. Nodes may have additional properties depending on their label.
Common patterns:
- (alloy:Alloy)-[:CONTAINS]->(element:Element) with weight property on the relationship
- (alloy:Alloy)-[:HAS_PROPERTY]->(prop:Property) where prop has value, unit properties
- (alloy:Alloy)-[:PROCESSED_BY]->(process:Process) with order property

## Task
Translate the following natural language question into a Cypher query.

Question: {question}

## Rules
1. Return ONLY valid Neo4j Cypher — no explanation outside the format below
2. Always include LIMIT {limit} unless the user specifically asks for all results
3. Use parameterized queries with $param syntax where appropriate
4. For text matching, use `toLower(n.name) CONTAINS toLower('...')` for case-insensitive search
5. Return useful columns (not raw node objects) — name, type, properties, values

## Response Format
Respond with exactly two lines:
CYPHER: <your cypher query here>
EXPLANATION: <one sentence explaining what the query does>"#
    )
}

fn parse_response(response: &str) -> Result<TranslationResult> {
    let mut cypher = None;
    let mut explanation = None;

    for line in response.lines() {
        let trimmed = line.trim();
        if let Some(c) = trimmed.strip_prefix("CYPHER:") {
            cypher = Some(c.trim().to_string());
        } else if let Some(e) = trimmed.strip_prefix("EXPLANATION:") {
            explanation = Some(e.trim().to_string());
        }
    }

    // Fallback: if the LLM didn't follow the format exactly, try to extract
    // Cypher from the first line that looks like a query
    let cypher = cypher.or_else(|| {
        response
            .lines()
            .map(str::trim)
            .find(|line| {
                let upper = line.to_uppercase();
                upper.starts_with("MATCH")
                    || upper.starts_with("RETURN")
                    || upper.starts_with("CALL")
                    || upper.starts_with("WITH")
            })
            .map(String::from)
    });

    let Some(cypher) = cypher else {
        bail!(
            "LLM did not produce a valid Cypher query. Raw response:\n{}",
            &response[..response.len().min(500)]
        );
    };

    // Strip markdown code fences if the LLM wrapped it
    let cypher = cypher
        .trim_start_matches("```cypher")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim()
        .to_string();

    Ok(TranslationResult {
        cypher,
        explanation: explanation
            .unwrap_or_else(|| "Query translated from natural language.".into()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_well_formatted_response() {
        let resp =
            "CYPHER: MATCH (a:Alloy) RETURN a.name LIMIT 10\nEXPLANATION: Returns all alloy names.";
        let result = parse_response(resp).unwrap();
        assert!(result.cypher.starts_with("MATCH"));
        assert!(result.explanation.contains("alloy"));
    }

    #[test]
    fn parse_response_with_code_fences() {
        let resp = "CYPHER: ```MATCH (a:Alloy) RETURN a.name```\nEXPLANATION: Gets alloys.";
        let result = parse_response(resp).unwrap();
        assert!(result.cypher.starts_with("MATCH"));
        assert!(!result.cypher.contains("```"));
    }

    #[test]
    fn parse_response_fallback_to_match_line() {
        let resp = "Here's a query:\nMATCH (a:Alloy) WHERE a.name = 'NbMoTaW' RETURN a";
        let result = parse_response(resp).unwrap();
        assert!(result.cypher.contains("MATCH"));
    }

    #[test]
    fn parse_response_no_cypher_fails() {
        let resp = "I don't understand the question.";
        assert!(parse_response(resp).is_err());
    }

    #[test]
    fn build_prompt_includes_schema() {
        let schema = GraphSchemaInfo {
            labels: vec!["Alloy".into(), "Element".into()],
            relationship_types: vec!["CONTAINS".into()],
        };
        let prompt = build_prompt("find all alloys", &schema, 10);
        assert!(prompt.contains("Alloy, Element"));
        assert!(prompt.contains("CONTAINS"));
        assert!(prompt.contains("find all alloys"));
    }
}
