"""Serve CLI command: start PRISM as an MCP server."""
import json

import click
from rich.console import Console


def _generate_nginx_config(host: str, port: int) -> str:
    """Generate an nginx reverse-proxy config for PRISM MCP server."""
    return f"""\
# PRISM MCP Server — nginx reverse proxy
# Generated by: prism serve --generate-nginx
#
# Usage:
#   1. Save this to /etc/nginx/sites-available/prism-mcp
#   2. ln -s /etc/nginx/sites-available/prism-mcp /etc/nginx/sites-enabled/
#   3. nginx -t && systemctl reload nginx
#
# The upstream PRISM server must be running:
#   prism serve --transport http --host {host} --port {port}

upstream prism_mcp {{
    server {host}:{port};
}}

server {{
    listen 80;
    server_name _;

    # MCP streamable-http endpoint
    location /mcp {{
        proxy_pass http://prism_mcp/mcp;
        proxy_http_version 1.1;

        # SSE / streaming support
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding on;

        # Standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Long timeout for tool execution
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }}

    # Health check
    location /health {{
        proxy_pass http://prism_mcp/mcp;
        proxy_method GET;
        access_log off;
    }}

    # Deny everything else
    location / {{
        return 404;
    }}
}}
"""


@click.command("serve")
@click.option("--transport", default="stdio", type=click.Choice(["stdio", "http"]),
              help="MCP transport (stdio for Claude Desktop, http for web)")
@click.option("--host", default="127.0.0.1", help="Bind address (default: 127.0.0.1, use 0.0.0.0 for all interfaces)")
@click.option("--port", default=8000, type=int, help="HTTP port (only for http transport)")
@click.option("--install", is_flag=True, help="Print Claude Desktop configuration JSON and exit")
@click.option("--generate-nginx", is_flag=True, help="Print nginx reverse-proxy config and exit")
def serve(transport, host, port, install, generate_nginx):
    """Start PRISM as an MCP server for external LLM hosts."""
    console = Console(force_terminal=True, width=120)

    if install:
        from app.mcp_server import generate_claude_desktop_config
        config = generate_claude_desktop_config()
        console.print(json.dumps(config, indent=2))
        return

    if generate_nginx:
        click.echo(_generate_nginx_config(host, port))
        return

    from app.mcp_server import create_mcp_server
    server = create_mcp_server()
    if transport == "http":
        console.print(f"[bold cyan]PRISM MCP Server[/bold cyan] starting on http://{host}:{port}/mcp", err=True)
        server.run(transport="streamable-http", host=host, port=port)
    else:
        console.print("[bold cyan]PRISM MCP Server[/bold cyan] starting on stdio", err=True)
        server.run(transport="stdio")
