// Copyright (c) 2025-2026 MARC27. Licensed under MARC27 Source-Available License.
//! YAML workflow engine for PRISM.
//!
//! Discovers workflow definitions from `~/.prism/workflows/` and promotes them
//! to first-class CLI commands. A workflow is a DAG of tool-execution steps
//! with template interpolation (`{{ args.data }}`), parallel execution, and
//! dependency tracking.
//!
//! Any YAML file dropped into the workflows directory is automatically
//! available as `prism <workflow-name>` — no registration or compilation needed.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};
use chrono::Utc;
use serde::{Deserialize, Serialize};

const BUILTIN_FORGE_YAML: &str = include_str!("../../../app/workflows/builtin/forge.yaml");

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WorkflowArgument {
    pub name: String,
    #[serde(default = "default_string_type")]
    pub r#type: String,
    #[serde(default)]
    pub required: bool,
    // `description` is an alias for `help` — LLM-friendly: many YAML
    // dialects use `description:` to document arguments, including
    // skill_workflow and several upstream workflow specs. We accept
    // either spelling on input. See docs/workflows.md.
    #[serde(default, alias = "description")]
    pub help: String,
    #[serde(default)]
    pub default: Option<serde_json::Value>,
    #[serde(default)]
    pub env: String,
    #[serde(default)]
    pub is_flag: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WorkflowStep {
    // `id` is OPTIONAL on input — auto-generated by `load_workflow_from_str`
    // when missing (LLM-friendly path). The struct field is non-Option so
    // post-load consumers can rely on `id` always being populated.
    #[serde(default)]
    pub id: String,
    // `action` is OPTIONAL on input so we can produce a helpful error
    // message in load_workflow_from_str instead of a serde-internal one.
    // The loader rejects steps with empty action.
    #[serde(default)]
    pub action: String,
    #[serde(flatten)]
    pub config: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WorkflowSpec {
    pub name: String,
    pub description: String,
    pub command_name: String,
    pub source_path: String,
    #[serde(default = "default_mode")]
    pub default_mode: String,
    #[serde(default)]
    pub arguments: Vec<WorkflowArgument>,
    #[serde(default)]
    pub steps: Vec<WorkflowStep>,
    #[serde(default)]
    pub raw: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WorkflowStepResult {
    pub id: String,
    pub action: String,
    pub status: String,
    pub summary: String,
    #[serde(default)]
    pub data: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WorkflowRunResult {
    pub workflow: String,
    pub mode: String,
    pub context: BTreeMap<String, serde_json::Value>,
    pub steps: Vec<WorkflowStepResult>,
}

#[derive(Debug, Clone)]
pub struct WorkflowCommandRequest {
    pub name: String,
    pub execute: bool,
    pub values: BTreeMap<String, String>,
}

#[derive(Debug, Deserialize)]
struct WorkflowManifest {
    #[serde(default)]
    kind: String,
    name: Option<String>,
    command_name: Option<String>,
    description: Option<String>,
    #[serde(default = "default_mode")]
    default_mode: String,
    // `inputs` is an alias for `arguments` — the skill_workflow dialect
    // uses `inputs:` while the workflow dialect canonically uses
    // `arguments:`. Both are accepted on input. See docs/workflows.md.
    #[serde(default, alias = "inputs")]
    arguments: Vec<WorkflowArgument>,
    // `tasks` is a legacy alias for `steps` (pre-1.0 PRISM workflow files).
    #[serde(default, alias = "tasks")]
    steps: Vec<WorkflowStep>,
}

fn default_string_type() -> String {
    "string".to_string()
}

fn default_mode() -> String {
    "dry_run".to_string()
}

fn builtin_workflows() -> Result<Vec<WorkflowSpec>> {
    Ok(vec![load_workflow_from_str(
        BUILTIN_FORGE_YAML,
        "builtin:forge.yaml",
    )?])
}

pub fn workflow_search_paths(project_root: Option<&Path>) -> Vec<PathBuf> {
    let mut paths = Vec::new();
    let root = project_root
        .map(Path::to_path_buf)
        .unwrap_or_else(|| env::current_dir().unwrap_or_else(|_| PathBuf::from(".")));
    paths.push(root.join(".prism").join("workflows"));
    if let Some(home) = env::var_os("HOME") {
        paths.push(PathBuf::from(home).join(".prism").join("workflows"));
    }
    paths
}

pub fn discover_workflows(project_root: Option<&Path>) -> Result<BTreeMap<String, WorkflowSpec>> {
    let mut specs = BTreeMap::new();
    for spec in builtin_workflows()? {
        specs.insert(spec.name.clone(), spec);
    }

    for directory in workflow_search_paths(project_root) {
        if !directory.is_dir() {
            continue;
        }
        for entry in fs::read_dir(&directory)
            .with_context(|| format!("failed to read workflow directory {}", directory.display()))?
        {
            let entry = entry?;
            let path = entry.path();
            if !path.is_file() {
                continue;
            }
            let ext = path
                .extension()
                .and_then(|e| e.to_str())
                .unwrap_or_default();
            if ext != "yml" && ext != "yaml" {
                continue;
            }
            // Per-file failures are logged and skipped. One malformed YAML
            // shouldn't break discovery for the user's other workflows —
            // previously the `?` here propagated upward and made every
            // `prism workflow list` (and every chat startup that loads
            // workflows) fail with the first parse error encountered.
            let text = match fs::read_to_string(&path) {
                Ok(t) => t,
                Err(e) => {
                    tracing::warn!(
                        path = %path.display(),
                        error = %e,
                        "skipping workflow file: read failed"
                    );
                    continue;
                }
            };
            match load_workflow_from_str(&text, &path.display().to_string()) {
                Ok(spec) => {
                    specs.insert(spec.name.clone(), spec);
                }
                Err(e) => {
                    tracing::warn!(
                        path = %path.display(),
                        error = %format!("{e:#}"),
                        "skipping workflow file: parse failed"
                    );
                }
            }
        }
    }

    Ok(specs)
}

pub fn find_workflow<'a>(
    specs: &'a BTreeMap<String, WorkflowSpec>,
    name: &str,
) -> Option<&'a WorkflowSpec> {
    specs
        .get(name)
        .or_else(|| specs.values().find(|spec| spec.command_name == name))
}

pub fn parse_workflow_command_args(args: &[String]) -> Result<WorkflowCommandRequest> {
    if args.is_empty() {
        bail!("workflow command name is required");
    }

    let name = args[0].clone();
    let mut values = BTreeMap::new();
    let mut execute = false;
    let mut index = 1;

    while index < args.len() {
        let arg = &args[index];
        if arg == "--execute" {
            execute = true;
            index += 1;
            continue;
        }
        if !arg.starts_with("--") {
            bail!("unexpected positional argument: {arg}");
        }
        let key = arg.trim_start_matches("--").replace('-', "_");
        if index + 1 < args.len() && !args[index + 1].starts_with("--") {
            values.insert(key, args[index + 1].clone());
            index += 2;
        } else {
            values.insert(key, "true".to_string());
            index += 1;
        }
    }

    Ok(WorkflowCommandRequest {
        name,
        execute,
        values,
    })
}

pub fn build_initial_context(
    spec: &WorkflowSpec,
    values: &BTreeMap<String, String>,
) -> Result<BTreeMap<String, serde_json::Value>> {
    let mut context = BTreeMap::new();
    for (key, value) in values {
        context.insert(key.clone(), serde_json::Value::String(value.clone()));
    }

    for argument in &spec.arguments {
        let missing = match context.get(&argument.name) {
            Some(value) => value == "" || value.is_null(),
            None => true,
        };
        if missing {
            if !argument.env.is_empty()
                && let Ok(value) = env::var(&argument.env)
                && !value.is_empty()
            {
                context.insert(argument.name.clone(), serde_json::Value::String(value));
                continue;
            }
            if let Some(default) = &argument.default {
                context.insert(argument.name.clone(), default.clone());
                continue;
            }
        }
        if argument.required
            && context
                .get(&argument.name)
                .is_none_or(|value| value.is_null() || value == "")
            && !argument.is_flag
        {
            bail!("missing required workflow argument: {}", argument.name);
        }
        context
            .entry(argument.name.clone())
            .or_insert(serde_json::Value::Null);
    }

    context
        .entry("workflow_name".to_string())
        .or_insert_with(|| serde_json::Value::String(spec.name.clone()));
    context
        .entry("command_name".to_string())
        .or_insert_with(|| serde_json::Value::String(spec.command_name.clone()));
    context
        .entry("now_iso".to_string())
        .or_insert_with(|| serde_json::Value::String(Utc::now().to_rfc3339()));
    Ok(context)
}

pub async fn execute_workflow(
    spec: &WorkflowSpec,
    values: &BTreeMap<String, String>,
    execute: bool,
) -> Result<WorkflowRunResult> {
    execute_workflow_with_policy(spec, values, execute, None, None).await
}

/// Execute a workflow with optional OPA policy enforcement.
///
/// When a `PolicyEngine` is provided, the engine checks:
/// 1. Whether the principal is allowed to execute this workflow at all
/// 2. Whether each `tool` step is allowed before execution
///
/// The `principal` should be the user ID or "agent" for autonomous execution.
pub async fn execute_workflow_with_policy(
    spec: &WorkflowSpec,
    values: &BTreeMap<String, String>,
    execute: bool,
    mut policy: Option<&mut prism_policy::PolicyEngine>,
    principal: Option<&str>,
) -> Result<WorkflowRunResult> {
    let principal = principal.unwrap_or("agent");

    // Check workflow-level policy and collect obligations
    let mut workflow_obligations: Vec<String> = Vec::new();
    if let Some(engine) = policy.as_deref_mut() {
        let input = prism_policy::PolicyInput {
            action: "workflow.execute".into(),
            principal: principal.into(),
            role: values
                .get("role")
                .cloned()
                .unwrap_or_else(|| "operator".into()),
            resource: spec.name.clone(),
            context: serde_json::json!({
                "execute": execute,
                "step_count": spec.steps.len(),
            }),
        };
        let decision = engine
            .require(&input)
            .with_context(|| format!("policy denied workflow '{}'", spec.name))?;
        workflow_obligations = decision.obligations;
    }

    let mut context = build_initial_context(spec, values)?;

    // ── Run on_start hooks ─────────────────────────────────────────
    let hooks = spec
        .raw
        .as_object()
        .and_then(|o| o.get("hooks"))
        .cloned()
        .unwrap_or(serde_json::Value::Null);
    let client = reqwest::Client::new();
    if let Some(on_start_steps) = hooks
        .get("on_start")
        .and_then(|v| serde_json::from_value::<Vec<WorkflowStep>>(v.clone()).ok())
    {
        for hook_step in &on_start_steps {
            let _ = match hook_step.action.as_str() {
                "set" => run_set_step(hook_step, &mut context, !execute),
                "message" => run_message_step(hook_step, &mut context, !execute),
                "http" => run_http_step(hook_step, &mut context, !execute, &client).await,
                _ => Ok(WorkflowStepResult {
                    id: hook_step.id.clone(),
                    action: hook_step.action.clone(),
                    status: "skipped".into(),
                    summary: "unsupported hook action".into(),
                    data: serde_json::Value::Null,
                }),
            };
        }
    }

    // ── Fulfill audit_log obligation ───────────────────────────────
    if workflow_obligations.contains(&"audit_log".to_string()) {
        tracing::info!(
            workflow = %spec.name,
            principal,
            execute,
            "AUDIT: workflow execution started"
        );
        context.insert(
            "_audit".to_string(),
            serde_json::json!({
                "workflow": spec.name,
                "principal": principal,
                "started_at": chrono::Utc::now().to_rfc3339(),
                "obligations": workflow_obligations,
            }),
        );
    }
    let mut result = WorkflowRunResult {
        workflow: spec.name.clone(),
        mode: if execute { "execute" } else { "dry_run" }.to_string(),
        context: context.clone(),
        steps: Vec::new(),
    };

    for step in &spec.steps {
        // Per-step policy check for tool calls.
        // Reads name + inputs through the same aliases the runner uses
        // so policy sees the same payload regardless of LLM-friendly
        // spelling: `name`/`tool`, `inputs`/`args`/`with`/`params`.
        if step.action == "tool"
            && let Some(engine) = policy.as_deref_mut()
        {
            let tool_name = config_first(&step.config, &["name", "tool"])
                .and_then(|v| v.as_str())
                .unwrap_or_default();
            let input = prism_policy::PolicyInput {
                action: "tool.call".into(),
                principal: principal.into(),
                role: values
                    .get("role")
                    .cloned()
                    .unwrap_or_else(|| "operator".into()),
                resource: tool_name.into(),
                context: config_first(&step.config, &["inputs", "args", "with", "params"])
                    .cloned()
                    .unwrap_or(serde_json::Value::Null),
            };
            engine.require(&input).with_context(|| {
                format!(
                    "policy denied tool '{}' in workflow step '{}'",
                    tool_name, step.id
                )
            })?;
        }

        // Retry wrapper — any step can have retry config
        let max_retries = step
            .config
            .get("retries")
            .and_then(|v| v.as_u64())
            .unwrap_or(0) as u32;
        let retry_delay_secs = step
            .config
            .get("retry_delay_secs")
            .and_then(|v| v.as_u64())
            .unwrap_or(2);

        let mut last_err = None;
        for attempt in 0..=max_retries {
            if attempt > 0 {
                if !execute {
                    break; // dry run doesn't retry
                }
                tracing::info!(
                    step = %step.id,
                    attempt,
                    "retrying workflow step after {}s",
                    retry_delay_secs * u64::from(attempt)
                );
                tokio::time::sleep(std::time::Duration::from_secs(
                    retry_delay_secs * u64::from(attempt),
                ))
                .await;
            }

            let step_result = match step.action.as_str() {
                "set" => run_set_step(step, &mut context, !execute),
                "message" => run_message_step(step, &mut context, !execute),
                "http" => run_http_step(step, &mut context, !execute, &client).await,
                "tool" => run_tool_step(step, &mut context, !execute, &client).await,
                "llm" => run_llm_step(step, &mut context, !execute).await,
                "if" => {
                    run_if_step(
                        step,
                        &mut context,
                        !execute,
                        &client,
                        policy.as_deref_mut(),
                        principal,
                    )
                    .await
                }
                "loop" => {
                    run_loop_step(
                        step,
                        &mut context,
                        !execute,
                        &client,
                        policy.as_deref_mut(),
                        principal,
                    )
                    .await
                }
                "parallel" => run_parallel_step(step, &mut context, !execute, &client).await,
                "workflow" => {
                    run_workflow_step(
                        step,
                        &mut context,
                        !execute,
                        policy.as_deref_mut(),
                        principal,
                    )
                    .await
                }
                other => bail!("unsupported workflow step action: {other}"),
            };

            match step_result {
                Ok(r) => {
                    result.steps.push(r);
                    last_err = None;
                    break;
                }
                Err(e) if attempt < max_retries && execute => {
                    tracing::warn!(step = %step.id, attempt, error = %e, "step failed, will retry");
                    last_err = Some(e);
                }
                Err(e) => return Err(e),
            }
        }
        if let Some(e) = last_err {
            return Err(e);
        }
    }

    // ── Run on_complete hooks ──────────────────────────────────────
    if let Some(on_complete_steps) = hooks
        .get("on_complete")
        .and_then(|v| serde_json::from_value::<Vec<WorkflowStep>>(v.clone()).ok())
    {
        for hook_step in &on_complete_steps {
            let _ = match hook_step.action.as_str() {
                "set" => run_set_step(hook_step, &mut context, !execute),
                "message" => run_message_step(hook_step, &mut context, !execute),
                "http" => run_http_step(hook_step, &mut context, !execute, &client).await,
                _ => Ok(WorkflowStepResult {
                    id: hook_step.id.clone(),
                    action: hook_step.action.clone(),
                    status: "skipped".into(),
                    summary: "unsupported hook action".into(),
                    data: serde_json::Value::Null,
                }),
            };
        }
    }

    // ── Fulfill notify_admin obligation ────────────────────────────
    if workflow_obligations.contains(&"notify_admin".to_string()) {
        tracing::warn!(
            workflow = %spec.name,
            principal,
            steps = result.steps.len(),
            "NOTIFY_ADMIN: agent executed workflow — review recommended"
        );
    }

    // ── Fulfill audit_log completion ───────────────────────────────
    if workflow_obligations.contains(&"audit_log".to_string()) {
        tracing::info!(
            workflow = %spec.name,
            principal,
            steps = result.steps.len(),
            mode = %result.mode,
            "AUDIT: workflow execution completed"
        );
    }

    // Never surface the injected loopback credential: strip it before the
    // context is returned (it's serialized into WorkflowRunResult.context,
    // which the CLI renders and the agent returns as a tool result).
    context.remove("_node_token");
    result.context = context;
    Ok(result)
}

/// Look up the first field in `config` that matches one of `keys`.
///
/// Used to accept a canonical field name plus LLM-friendly aliases —
/// e.g. `tool` step accepts `name` (canonical) or `tool`. The first
/// key in the slice is the canonical one used in errors.
fn config_first<'a>(
    config: &'a BTreeMap<String, serde_json::Value>,
    keys: &[&str],
) -> Option<&'a serde_json::Value> {
    keys.iter().find_map(|k| config.get(*k))
}

fn run_set_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
) -> Result<WorkflowStepResult> {
    // Aliases: `values` (canonical) | `vars` | `data`
    let values = render_value(
        config_first(&step.config, &["values", "vars", "data"])
            .cloned()
            .unwrap_or_else(|| serde_json::Value::Object(Default::default())),
        context,
    )?;
    context.insert(step.id.clone(), values.clone());
    if let Some(map) = values.as_object() {
        for (key, value) in map {
            context.insert(key.clone(), value.clone());
        }
    }
    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: if dry_run { "planned" } else { "completed" }.to_string(),
        summary: format!(
            "set {} value(s)",
            values.as_object().map(|m| m.len()).unwrap_or(1)
        ),
        data: serde_json::json!({ "values": values }),
    })
}

fn run_message_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
) -> Result<WorkflowStepResult> {
    // Aliases: `text` (canonical) | `body` | `content` | `msg`
    let text = render_value(
        config_first(&step.config, &["text", "body", "content", "msg"])
            .cloned()
            .unwrap_or_else(|| serde_json::Value::String(String::new())),
        context,
    )?;
    if !dry_run {
        context.insert(step.id.clone(), serde_json::json!({ "message": text }));
    }
    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: if dry_run { "planned" } else { "completed" }.to_string(),
        summary: interpolated_display(&text),
        data: serde_json::json!({ "message": text }),
    })
}

async fn run_http_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
    client: &reqwest::Client,
) -> Result<WorkflowStepResult> {
    let method = step
        .config
        .get("method")
        .and_then(|v| v.as_str())
        .unwrap_or("GET")
        .to_uppercase();
    let url = render_value(
        step.config
            .get("url")
            .cloned()
            .unwrap_or_else(|| serde_json::Value::String(String::new())),
        context,
    )?;
    let headers = render_value(
        step.config
            .get("headers")
            .cloned()
            .unwrap_or_else(|| serde_json::Value::Object(Default::default())),
        context,
    )?;
    let body = render_value(
        step.config
            .get("body")
            .cloned()
            .unwrap_or(serde_json::Value::Null),
        context,
    )?;
    let expect_status = step
        .config
        .get("expect_status")
        .cloned()
        .unwrap_or_else(|| serde_json::json!([200, 201, 202]));
    let expect_statuses = expected_statuses(&expect_status)?;

    if dry_run {
        return Ok(WorkflowStepResult {
            id: step.id.clone(),
            action: step.action.clone(),
            status: "planned".to_string(),
            summary: format!("{} {}", method, url.as_str().unwrap_or_default()),
            data: serde_json::json!({
                "method": method,
                "url": url,
                "headers": headers,
                "body": body,
            }),
        });
    }

    let method = reqwest::Method::from_bytes(method.as_bytes())
        .with_context(|| format!("invalid HTTP method for workflow step {}", step.id))?;

    // SSRF guard — workflows are arbitrary YAML, including marketplace
    // installs and LLM-generated specs. Without this, a workflow with
    // url: http://169.254.169.254/... would hit AWS instance metadata
    // and leak IAM creds; url: http://localhost:7327/api/users would
    // hit PRISM's own admin API. See Bug #56.
    let url_str = url.as_str().unwrap_or_default();
    if let Some(reason) = ssrf_block_reason(url_str) {
        bail!(
            "workflow step {} url {url_str:?} rejected by SSRF guard: {reason}",
            step.id
        );
    }
    let mut request = client.request(method, url_str);
    if let Some(map) = headers.as_object() {
        for (key, value) in map {
            if let Some(value) = value.as_str() {
                request = request.header(key, value);
            }
        }
    }
    if !body.is_null() {
        request = request.json(&body);
    }
    let response = request.send().await?;
    let status = response.status();
    let status_code = status.as_u16();
    if !expect_statuses.contains(&status_code) {
        bail!(
            "workflow step {} expected status {:?} but got {}",
            step.id,
            expect_statuses,
            status_code
        );
    }
    let headers_map = response
        .headers()
        .iter()
        .map(|(key, value)| {
            (
                key.to_string(),
                serde_json::Value::String(value.to_str().unwrap_or_default().to_string()),
            )
        })
        .collect::<serde_json::Map<String, serde_json::Value>>();
    let text = response.text().await?;
    let parsed_body =
        serde_json::from_str(&text).unwrap_or_else(|_| serde_json::json!({ "text": text }));
    let stored = serde_json::json!({
        "status_code": status_code,
        "headers": headers_map,
        "body": parsed_body,
    });
    context.insert(step.id.clone(), stored.clone());
    context.insert("last_response".to_string(), stored.clone());
    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: "completed".to_string(),
        summary: summarize_http_response(status_code, &parsed_body),
        data: serde_json::json!({
            "request": {
                "method": step.config.get("method").cloned().unwrap_or_else(|| serde_json::Value::String("GET".to_string())),
                "url": url,
            },
            "response": stored,
        }),
    })
}

/// Execute a tool on the local PRISM node via `POST /api/tools/{name}/run`.
///
/// YAML config:
/// ```yaml
/// - id: train
///   action: tool
///   name: ml-pipeline
///   command: train
///   inputs:
///     data: "{{ data }}"
///     target: hardness
/// ```
async fn run_tool_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
    client: &reqwest::Client,
) -> Result<WorkflowStepResult> {
    // Aliases: `name` (canonical) | `tool`
    let tool_name = config_first(&step.config, &["name", "tool"])
        .and_then(|v| v.as_str())
        .ok_or_else(|| anyhow!("tool step '{}' missing 'name' field", step.id))?
        .to_string();

    // Aliases: `command` (canonical) | `cmd`
    let command = render_value(
        config_first(&step.config, &["command", "cmd"])
            .cloned()
            .unwrap_or(serde_json::Value::Null),
        context,
    )?;

    // Aliases: `inputs` (canonical) | `args` | `with` | `params`
    let inputs = render_value(
        config_first(&step.config, &["inputs", "args", "with", "params"])
            .cloned()
            .unwrap_or_else(|| serde_json::Value::Object(Default::default())),
        context,
    )?;

    // Approval gate. Approval-gated tools (execute_python, compute_submit,
    // predict, research, sim_run, …) refuse to run headless unless the caller
    // pre-approves them by name. A workflow author who writes `approve: true`
    // on a tool step IS that pre-approval — the deterministic equivalent of a
    // chat turn's interactive OK — and the node's `/api/tools/{name}/run`
    // endpoint already honours a top-level `approve` in the body. This is NOT a
    // policy bypass: every tool step is still checked by OPA, which gates
    // destructive tools by role regardless of this flag. Aliases mirror the
    // natural things an author (or LLM) writes.
    let approve = config_first(&step.config, &["approve", "approved", "auto_approve"])
        .and_then(|v| v.as_bool())
        .unwrap_or(false);

    if dry_run {
        return Ok(WorkflowStepResult {
            id: step.id.clone(),
            action: step.action.clone(),
            status: "planned".to_string(),
            summary: format!("tool:{tool_name} {}", command.as_str().unwrap_or_default()),
            data: serde_json::json!({
                "tool": tool_name,
                "command": command,
                "inputs": inputs,
                "approve": approve,
            }),
        });
    }

    // Call the local PRISM node API
    let port = context
        .get("node_port")
        .and_then(|v| v.as_u64())
        .unwrap_or(7327);

    let url = format!("http://127.0.0.1:{port}/api/tools/{tool_name}/run");
    let body = serde_json::json!({
        "command": command,
        "inputs": inputs,
        "approve": approve,
    });

    // Authenticate to the local node. When the node is online it gates
    // `/api/tools/{name}/run` behind a session token (+ ExecuteTools), so a
    // tokenless call 401s. The caller (CLI `workflow run`, or the agent)
    // injects a loopback-minted session token into the context under the
    // reserved `_node_token` key; we forward it as a Bearer credential. The
    // key is stripped from the returned context so it never leaks into
    // rendered output or the agent's tool result. Absent token ⇒ no header
    // (works in offline mode, and fails honestly with 401 when online).
    let mut req = client.post(&url).json(&body);
    if let Some(token) = context
        .get("_node_token")
        .and_then(|v| v.as_str())
        .filter(|t| !t.is_empty())
    {
        req = req.header("Authorization", format!("Bearer {token}"));
    }

    let resp = req
        .send()
        .await
        .with_context(|| format!("failed to call tool '{tool_name}' at {url}"))?;

    let status_code = resp.status().as_u16();
    let resp_body: serde_json::Value = resp
        .json()
        .await
        .unwrap_or_else(|_| serde_json::json!({"error": "failed to parse response"}));

    if status_code >= 400 {
        bail!(
            "tool '{}' returned HTTP {}: {}",
            tool_name,
            status_code,
            resp_body
        );
    }

    let stored = serde_json::json!({
        "status_code": status_code,
        "output": resp_body,
    });
    context.insert(step.id.clone(), stored.clone());

    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: "completed".to_string(),
        summary: format!("tool:{tool_name} → HTTP {status_code}"),
        data: stored,
    })
}

// ── Conditional step ─────────────────────────────────────────────────
//
// YAML:
//   - id: check
//     action: if
//     condition: "{{ kg_search.body.count }}"  # truthy check
//     then:
//       - id: found
//         action: message
//         text: "Found materials"
//     else:
//       - id: not_found
//         action: message
//         text: "No materials found"
//
async fn run_if_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
    client: &reqwest::Client,
    _policy: Option<&mut prism_policy::PolicyEngine>,
    _principal: &str,
) -> Result<WorkflowStepResult> {
    // Aliases: `condition` (canonical) | `cond` | `when` | `if`
    let condition_raw = render_value(
        config_first(&step.config, &["condition", "cond", "when", "if"])
            .cloned()
            .unwrap_or(serde_json::Value::Null),
        context,
    )?;

    let is_truthy = match &condition_raw {
        serde_json::Value::Null => false,
        serde_json::Value::Bool(b) => *b,
        serde_json::Value::String(s) => !s.is_empty() && s != "false" && s != "0" && s != "null",
        serde_json::Value::Number(n) => n.as_f64().is_some_and(|v| v != 0.0),
        serde_json::Value::Array(a) => !a.is_empty(),
        serde_json::Value::Object(o) => !o.is_empty(),
    };

    let branch_key = if is_truthy { "then" } else { "else" };
    let branch_steps: Vec<WorkflowStep> = step
        .config
        .get(branch_key)
        .and_then(|v| serde_json::from_value(v.clone()).ok())
        .unwrap_or_default();

    let mut sub_results = Vec::new();
    for sub_step in &branch_steps {
        let sub_result = match sub_step.action.as_str() {
            "set" => run_set_step(sub_step, context, dry_run)?,
            "message" => run_message_step(sub_step, context, dry_run)?,
            "http" => run_http_step(sub_step, context, dry_run, client).await?,
            "tool" => run_tool_step(sub_step, context, dry_run, client).await?,
            other => bail!("unsupported step action in if branch: {other}"),
        };
        sub_results.push(sub_result);
    }

    let summary = format!(
        "if {} → {} ({} steps)",
        if is_truthy { "true" } else { "false" },
        branch_key,
        sub_results.len()
    );

    context.insert(
        step.id.clone(),
        serde_json::json!({
            "branch": branch_key,
            "condition": condition_raw,
            "steps": sub_results.iter().map(|r| &r.id).collect::<Vec<_>>(),
        }),
    );

    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: if dry_run { "planned" } else { "completed" }.to_string(),
        summary,
        data: serde_json::json!({
            "branch": branch_key,
            "condition": condition_raw,
            "sub_steps": sub_results,
        }),
    })
}

// ── LLM step ─────────────────────────────────────────────────────────
//
// Calls the PRISM LLM client with a templated prompt and stores the
// response in the workflow context.  This is the bridge between the
// deterministic workflow DAG and the agentic layer: the LLM can reason
// over prior step outputs, decide what to do next, or generate
// natural-language summaries that downstream `tool` / `http` steps use
// as inputs.
//
// YAML:
//   - id: reason
//     action: llm
//     prompt: |
//       Given these search results: {{ search.body }}
//       Which 3 materials are most promising for {{ goal }}?
//     model: gemma-4-12b          # optional; defaults to config
//     system: "You are a materials scientist."  # optional
//     temperature: 0.7            # optional
//     max_tokens: 2000            # optional
//     output_key: recommendations # optional; defaults to step id
//
// The response text is stored under `context[output_key]` as a string.
// If the LLM call fails, the step errors (subject to the retry wrapper).
async fn run_llm_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
) -> Result<WorkflowStepResult> {
    let prompt = render_value(
        config_first(&step.config, &["prompt", "text", "input"])
            .cloned()
            .unwrap_or_else(|| serde_json::Value::String(String::new())),
        context,
    )?;
    let prompt_str = if let Some(s) = prompt.as_str() {
        s.to_string()
    } else {
        prompt.to_string()
    };

    let system = render_value(
        step.config
            .get("system")
            .cloned()
            .unwrap_or(serde_json::Value::Null),
        context,
    )?;
    let system_str = system.as_str().map(str::to_string);

    let model = step
        .config
        .get("model")
        .and_then(|v| v.as_str())
        .unwrap_or("");
    let _temperature = step
        .config
        .get("temperature")
        .and_then(|v| v.as_f64())
        .unwrap_or(0.7);
    let _max_tokens = step
        .config
        .get("max_tokens")
        .and_then(|v| v.as_u64())
        .unwrap_or(2000) as usize;

    let output_key = step
        .config
        .get("output_key")
        .and_then(|v| v.as_str())
        .unwrap_or(&step.id)
        .to_string();

    if dry_run {
        return Ok(WorkflowStepResult {
            id: step.id.clone(),
            action: step.action.clone(),
            status: "planned".to_string(),
            summary: format!("llm prompt ({} chars) → {}", prompt_str.len(), output_key),
            data: serde_json::json!({
                "prompt": &prompt_str,
                "model": model,
                "system": system_str,
                "output_key": output_key,
            }),
        });
    }

    // Build the LLM client from env/config. We use the same env vars
    // that `prism backend` uses so a workflow running on a PRISM node
    // hits the same LLM endpoint the agent uses.
    let base_url = env::var("LLM_BASE_URL")
        .or_else(|_| env::var("LLM_API_BASE"))
        .unwrap_or_else(|_| "http://127.0.0.1:8081/v1".to_string());
    let api_key = env::var("LLM_API_KEY")
        .or_else(|_| env::var("MARC27_TOKEN"))
        .ok();
    let model = if model.is_empty() {
        env::var("LLM_MODEL").unwrap_or_else(|_| "gemma-4-12b".to_string())
    } else {
        model.to_string()
    };

    let config = prism_llm::LlmConfig {
        base_url,
        api_key,
        model,
        embedding_model: None,
        ..Default::default()
    };
    let model_name = config.model.clone();
    let client = prism_llm::LlmClient::new(config);

    let system_text = system_str.unwrap_or_default();
    let response_text = client
        .chat(&system_text, &prompt_str)
        .await
        .context("LLM call failed in workflow step")?;

    context.insert(
        output_key.clone(),
        serde_json::Value::String(response_text.clone()),
    );
    context.insert(
        step.id.clone(),
        serde_json::json!({
            "prompt": &prompt_str,
            "response": response_text,
            "model": model_name,
        }),
    );

    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: "completed".to_string(),
        summary: format!("llm → {} ({} chars)", output_key, response_text.len()),
        data: serde_json::json!({
            "prompt": &prompt_str,
            "response": response_text,
            "model": model_name,
        }),
    })
}

// ── Loop step ────────────────────────────────────────────────────────
//
// Repeats a block of sub-steps until a condition is met or max_iterations
// is reached.  The condition is evaluated after each iteration using the
// same truthiness rules as the `if` step.  The loop body has access to
// the parent context plus `loop_index` (0-based) and `loop_iteration`
// (1-based, human-friendly).
//
// YAML:
//   - id: discover
//     action: loop
//     max_iterations: 10
//     until: "{{ done }}"          # stop when this is truthy
//     steps:
//       - id: sample
//         action: tool
//         name: sample_material
//       - id: evaluate
//         action: tool
//         name: evaluate_material
//         inputs: { composition: "{{ sample.output }}" }
//       - id: check
//         action: set
//         values: { done: "{{ evaluate.output.score > 0.9 }}" }
//
// Safety: max_iterations defaults to 5 and is capped at 100 to prevent
// runaway loops in LLM-generated workflows.
async fn run_loop_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
    client: &reqwest::Client,
    mut policy: Option<&mut prism_policy::PolicyEngine>,
    principal: &str,
) -> Result<WorkflowStepResult> {
    let max_iterations = step
        .config
        .get("max_iterations")
        .and_then(|v| v.as_u64())
        .unwrap_or(5)
        .min(100) as usize;

    let until_expr = config_first(&step.config, &["until", "condition", "stop_when"])
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let body_steps: Vec<WorkflowStep> =
        config_first(&step.config, &["steps", "tasks", "body", "do"])
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .unwrap_or_default();

    if body_steps.is_empty() {
        bail!("loop step '{}' has no body steps", step.id);
    }

    if dry_run {
        return Ok(WorkflowStepResult {
            id: step.id.clone(),
            action: step.action.clone(),
            status: "planned".to_string(),
            summary: format!(
                "loop (max {} iterations, {} body steps)",
                max_iterations,
                body_steps.len()
            ),
            data: serde_json::json!({
                "max_iterations": max_iterations,
                "until": until_expr,
                "body_steps": body_steps.iter().map(|s| &s.id).collect::<Vec<_>>(),
            }),
        });
    }

    let mut iterations = 0usize;
    let mut all_sub_results = Vec::new();

    for i in 0..max_iterations {
        // Inject loop counters into context so body steps can reference them.
        context.insert("loop_index".into(), serde_json::json!(i));
        context.insert("loop_iteration".into(), serde_json::json!(i + 1));

        let mut iter_results = Vec::new();
        for body_step in &body_steps {
            let sub_result = match body_step.action.as_str() {
                "set" => run_set_step(body_step, context, dry_run),
                "message" => run_message_step(body_step, context, dry_run),
                "http" => run_http_step(body_step, context, dry_run, client).await,
                "tool" => run_tool_step(body_step, context, dry_run, client).await,
                "llm" => run_llm_step(body_step, context, dry_run).await,
                "if" => {
                    run_if_step(
                        body_step,
                        context,
                        dry_run,
                        client,
                        policy.as_deref_mut(),
                        principal,
                    )
                    .await
                }
                other => bail!("unsupported step action in loop body: {other}"),
            };
            iter_results.push(sub_result?);
        }

        all_sub_results.extend(iter_results);
        iterations = i + 1;

        // Evaluate the until condition. Empty until → always false (loop
        // runs to max_iterations).
        if !until_expr.is_empty() {
            let rendered = render_value(serde_json::Value::String(until_expr.clone()), context)?;
            let is_truthy = match &rendered {
                serde_json::Value::Null => false,
                serde_json::Value::Bool(b) => *b,
                serde_json::Value::String(s) => {
                    !s.is_empty() && s != "false" && s != "0" && s != "null"
                }
                serde_json::Value::Number(n) => n.as_f64().is_some_and(|v| v != 0.0),
                serde_json::Value::Array(a) => !a.is_empty(),
                serde_json::Value::Object(o) => !o.is_empty(),
            };
            if is_truthy {
                break;
            }
        }
    }

    // Clean up loop counters from parent context.
    context.remove("loop_index");
    context.remove("loop_iteration");

    context.insert(
        step.id.clone(),
        serde_json::json!({
            "iterations": iterations,
            "until": until_expr,
            "completed": iterations < max_iterations,
        }),
    );

    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: "completed".to_string(),
        summary: format!(
            "loop: {} iteration(s){}",
            iterations,
            if iterations < max_iterations {
                " (until met)"
            } else {
                " (max reached)"
            }
        ),
        data: serde_json::json!({
            "iterations": iterations,
            "completed": iterations < max_iterations,
            "sub_steps": all_sub_results,
        }),
    })
}

// ── Parallel step ────────────────────────────────────────────────────
//
// YAML:
//   - id: fan_out
//     action: parallel
//     steps:
//       - id: search_mp
//         action: http
//         url: "https://api.materialsproject.org/..."
//       - id: search_nomad
//         action: http
//         url: "https://nomad-lab.eu/..."
//
async fn run_parallel_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
    client: &reqwest::Client,
) -> Result<WorkflowStepResult> {
    // Aliases: `steps` (canonical) | `tasks` | `branches`
    let sub_steps: Vec<WorkflowStep> = config_first(&step.config, &["steps", "tasks", "branches"])
        .and_then(|v| serde_json::from_value(v.clone()).ok())
        .unwrap_or_default();

    if dry_run {
        let summaries: Vec<String> = sub_steps
            .iter()
            .map(|s| format!("{}:{}", s.action, s.id))
            .collect();
        return Ok(WorkflowStepResult {
            id: step.id.clone(),
            action: step.action.clone(),
            status: "planned".to_string(),
            summary: format!(
                "parallel {} steps: {}",
                sub_steps.len(),
                summaries.join(", ")
            ),
            data: serde_json::json!({ "step_count": sub_steps.len(), "steps": summaries }),
        });
    }

    // Execute all sub-steps concurrently via tokio::join
    let mut handles = Vec::new();
    for sub_step in &sub_steps {
        let sub_step = sub_step.clone();
        let mut sub_context = context.clone();
        let client = client.clone();
        handles.push(tokio::spawn(async move {
            let result = match sub_step.action.as_str() {
                "set" => run_set_step(&sub_step, &mut sub_context, false),
                "message" => run_message_step(&sub_step, &mut sub_context, false),
                "http" => run_http_step(&sub_step, &mut sub_context, false, &client).await,
                "tool" => run_tool_step(&sub_step, &mut sub_context, false, &client).await,
                other => Err(anyhow!("unsupported step action in parallel: {other}")),
            };
            (sub_step.id.clone(), result, sub_context)
        }));
    }

    let mut sub_results = Vec::new();
    for handle in handles {
        let (sub_id, result, sub_context): (String, Result<WorkflowStepResult>, _) =
            handle.await.context("parallel step panicked")?;
        let step_result = result.with_context(|| format!("parallel sub-step '{sub_id}' failed"))?;
        // Merge sub-step context back into parent
        for (key, value) in sub_context {
            if !context.contains_key(&key) || key == sub_id {
                context.insert(key, value);
            }
        }
        sub_results.push(step_result);
    }

    context.insert(
        step.id.clone(),
        serde_json::json!({
            "completed": sub_results.len(),
            "steps": sub_results.iter().map(|r| &r.id).collect::<Vec<_>>(),
        }),
    );

    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: "completed".to_string(),
        summary: format!("parallel {} steps completed", sub_results.len()),
        data: serde_json::json!({ "sub_steps": sub_results }),
    })
}

// ── Sub-workflow step ────────────────────────────────────────────────
//
// YAML:
//   - id: train
//     action: workflow
//     name: forge
//     inputs:
//       paper: "{{ paper }}"
//       dataset: "{{ candidates }}"
//
async fn run_workflow_step(
    step: &WorkflowStep,
    context: &mut BTreeMap<String, serde_json::Value>,
    dry_run: bool,
    policy: Option<&mut prism_policy::PolicyEngine>,
    principal: &str,
) -> Result<WorkflowStepResult> {
    // Aliases: `name` (canonical) | `workflow`
    let workflow_name = config_first(&step.config, &["name", "workflow"])
        .and_then(|v| v.as_str())
        .ok_or_else(|| anyhow!("workflow step '{}' missing 'name' field", step.id))?;

    // Aliases: `inputs` (canonical) | `args` | `with`
    let inputs = render_value(
        config_first(&step.config, &["inputs", "args", "with"])
            .cloned()
            .unwrap_or_else(|| serde_json::Value::Object(Default::default())),
        context,
    )?;

    // Convert inputs to string map for workflow args
    let mut values = BTreeMap::new();
    if let Some(obj) = inputs.as_object() {
        for (k, v) in obj {
            values.insert(
                k.clone(),
                v.as_str()
                    .map(str::to_string)
                    .unwrap_or_else(|| v.to_string()),
            );
        }
    }

    if dry_run {
        return Ok(WorkflowStepResult {
            id: step.id.clone(),
            action: step.action.clone(),
            status: "planned".to_string(),
            summary: format!("workflow:{workflow_name} ({} inputs)", values.len()),
            data: serde_json::json!({
                "workflow": workflow_name,
                "inputs": inputs,
            }),
        });
    }

    // Discover and run the child workflow
    let project_root = context
        .get("project_root")
        .and_then(|v| v.as_str())
        .map(std::path::Path::new);
    let specs = discover_workflows(project_root)?;
    let child_spec = find_workflow(&specs, workflow_name)
        .ok_or_else(|| anyhow!("sub-workflow '{}' not found", workflow_name))?;

    let child_result = Box::pin(execute_workflow_with_policy(
        child_spec,
        &values,
        true,
        policy,
        Some(principal),
    ))
    .await?;

    // Merge child context into parent under the step id
    context.insert(step.id.clone(), serde_json::to_value(&child_result)?);

    Ok(WorkflowStepResult {
        id: step.id.clone(),
        action: step.action.clone(),
        status: "completed".to_string(),
        summary: format!(
            "workflow:{workflow_name} → {} steps completed",
            child_result.steps.len()
        ),
        data: serde_json::to_value(&child_result)?,
    })
}

fn expected_statuses(value: &serde_json::Value) -> Result<Vec<u16>> {
    match value {
        serde_json::Value::Number(num) => Ok(vec![
            num.as_u64().ok_or_else(|| anyhow!("invalid status code"))? as u16,
        ]),
        serde_json::Value::Array(items) => items
            .iter()
            .map(|item| {
                item.as_u64()
                    .map(|code| code as u16)
                    .ok_or_else(|| anyhow!("invalid status code"))
            })
            .collect(),
        _ => bail!("expect_status must be an integer or list of integers"),
    }
}

fn summarize_http_response(status_code: u16, parsed: &serde_json::Value) -> String {
    if let Some(id) = parsed.get("id") {
        return format!("HTTP {} id={}", status_code, json_display(id));
    }
    if let Some(count) = parsed.get("count") {
        return format!("HTTP {} count={}", status_code, json_display(count));
    }
    format!("HTTP {}", status_code)
}

fn json_display(value: &serde_json::Value) -> String {
    value
        .as_str()
        .map(str::to_string)
        .unwrap_or_else(|| value.to_string())
}

fn interpolated_display(value: &serde_json::Value) -> String {
    if value.is_null() {
        String::new()
    } else {
        json_display(value)
    }
}

/// Known step actions. Used both for validation and for `did you mean?`
/// suggestions on typos in LLM-generated workflows.
const KNOWN_ACTIONS: &[&str] = &[
    "set", "message", "http", "tool", "llm", "if", "loop", "parallel", "workflow",
];

/// Cheap edit-distance for "did you mean?" suggestions on action typos.
/// Pure ASCII Levenshtein, capped at length 32 to avoid pathological inputs.
fn edit_distance(a: &str, b: &str) -> usize {
    let a = &a[..a.len().min(32)];
    let b = &b[..b.len().min(32)];
    let m = a.len();
    let n = b.len();
    if m == 0 {
        return n;
    }
    if n == 0 {
        return m;
    }
    let mut prev: Vec<usize> = (0..=n).collect();
    let mut curr = vec![0usize; n + 1];
    let a_bytes = a.as_bytes();
    let b_bytes = b.as_bytes();
    for i in 1..=m {
        curr[0] = i;
        for j in 1..=n {
            let cost = if a_bytes[i - 1] == b_bytes[j - 1] {
                0
            } else {
                1
            };
            curr[j] = (prev[j] + 1).min(curr[j - 1] + 1).min(prev[j - 1] + cost);
        }
        std::mem::swap(&mut prev, &mut curr);
    }
    prev[n]
}

/// Suggest the closest known action to `unknown` if it's within 2 edits.
fn suggest_action(unknown: &str) -> Option<&'static str> {
    let lc = unknown.to_ascii_lowercase();
    let mut best: Option<(&str, usize)> = None;
    for &known in KNOWN_ACTIONS {
        let d = edit_distance(&lc, known);
        // Note: `is_none_or` (Rust 1.82+) is the clippy-preferred form
        // over `map_or(true, ...)` for "None or matches predicate" checks.
        if d <= 2 && best.is_none_or(|(_, bd)| d < bd) {
            best = Some((known, d));
        }
    }
    best.map(|(s, _)| s)
}

pub fn load_workflow_from_str(text: &str, source_path: &str) -> Result<WorkflowSpec> {
    let raw_yaml: serde_yaml::Value = serde_yaml::from_str(text)
        .with_context(|| format!("failed to parse workflow YAML from {source_path}"))?;
    let manifest: WorkflowManifest = serde_yaml::from_str(text)
        .with_context(|| format!("failed to decode workflow manifest from {source_path}"))?;

    // Tolerate a few legacy / dialect aliases on `kind`. The agent's
    // skill_workflow runner picks up `kind: skill_workflow` files via a
    // different code path; here we only accept the deterministic
    // `workflow` dialect, so report a clear error when the wrong
    // dialect is fed to the wrong loader.
    let kind = if manifest.kind.is_empty() {
        "workflow"
    } else {
        manifest.kind.as_str()
    };
    let kind_normalized = match kind {
        // Legacy / alternate spellings accepted as `workflow`
        "prism_workflow" | "prism-workflow" | "workflow" => "workflow",
        other => other,
    };
    if kind_normalized != "workflow" {
        bail!(
            "{source_path}: kind = '{kind}' is not the deterministic-workflow dialect \
             this loader handles. Either set `kind: workflow` (or omit it) for the \
             deterministic dialect, or move the file to a path picked up by the \
             skill_workflow runner. See docs/workflows.md for the difference."
        );
    }

    let name = manifest.name.unwrap_or_else(|| source_path.to_string());
    let command_name = manifest
        .command_name
        .unwrap_or_else(|| name.replace('_', "-"));
    let description = manifest
        .description
        .unwrap_or_else(|| format!("Run workflow '{name}'"));

    // Auto-generate step IDs when missing AND validate `action` early.
    // LLM-generated workflows often omit `id:`; auto-generation is the
    // friendly path. Action typos get a "did you mean?" suggestion.
    let mut steps = manifest.steps;
    for (idx, step) in steps.iter_mut().enumerate() {
        if step.id.is_empty() {
            // Synthesize a stable ID. Action included so it's
            // recognizable in logs (`tool_0`, `http_3`, etc.).
            step.id = if !step.action.is_empty() {
                format!("{}_{idx}", step.action)
            } else {
                format!("step_{idx}")
            };
        }
        if step.action.is_empty() {
            bail!(
                "{source_path}: step '{}' (index {idx}) has no `action`. \
                 Valid actions: {}",
                step.id,
                KNOWN_ACTIONS.join(", "),
            );
        }
        if !KNOWN_ACTIONS.contains(&step.action.as_str()) {
            let hint = match suggest_action(&step.action) {
                Some(s) => format!(" Did you mean `action: {s}`?"),
                None => format!(" Valid actions: {}.", KNOWN_ACTIONS.join(", ")),
            };
            bail!(
                "{source_path}: step '{}' (index {idx}) has unknown action \
                 '{}'.{hint}",
                step.id,
                step.action,
            );
        }
    }

    let raw = serde_json::to_value(raw_yaml)?;
    Ok(WorkflowSpec {
        name,
        description,
        command_name,
        source_path: source_path.to_string(),
        default_mode: manifest.default_mode,
        arguments: manifest.arguments,
        steps,
        raw,
    })
}

fn render_value(
    value: serde_json::Value,
    context: &BTreeMap<String, serde_json::Value>,
) -> Result<serde_json::Value> {
    match value {
        serde_json::Value::String(text) => render_string(&text, context),
        serde_json::Value::Array(items) => {
            let rendered = items
                .into_iter()
                .map(|item| render_value(item, context))
                .collect::<Result<Vec<_>>>()?;
            Ok(serde_json::Value::Array(rendered))
        }
        serde_json::Value::Object(map) => {
            let mut rendered = serde_json::Map::new();
            for (key, value) in map {
                rendered.insert(key, render_value(value, context)?);
            }
            Ok(serde_json::Value::Object(rendered))
        }
        other => Ok(other),
    }
}

fn render_string(
    text: &str,
    context: &BTreeMap<String, serde_json::Value>,
) -> Result<serde_json::Value> {
    if !text.contains("{{") {
        return Ok(serde_json::Value::String(text.to_string()));
    }
    if let Some(path) = whole_template(text) {
        return resolve_path(context, path);
    }

    let mut rendered = String::new();
    let mut rest = text;
    while let Some(start) = rest.find("{{") {
        let (before, after_start) = rest.split_at(start);
        rendered.push_str(before);
        let after_start = &after_start[2..];
        let end = after_start
            .find("}}")
            .ok_or_else(|| anyhow!("unterminated workflow template in '{text}'"))?;
        let key = after_start[..end].trim();
        let resolved = resolve_path(context, key)?;
        rendered.push_str(&interpolated_display(&resolved));
        rest = &after_start[end + 2..];
    }
    rendered.push_str(rest);
    Ok(serde_json::Value::String(rendered))
}

fn whole_template(text: &str) -> Option<&str> {
    let trimmed = text.trim();
    if trimmed.starts_with("{{") && trimmed.ends_with("}}") {
        let inner = &trimmed[2..trimmed.len() - 2];
        if !inner.contains("{{") && !inner.contains("}}") {
            return Some(inner.trim());
        }
    }
    None
}

fn resolve_path(
    context: &BTreeMap<String, serde_json::Value>,
    path: &str,
) -> Result<serde_json::Value> {
    // `args.` is a documented convention, not a real container: docs/workflows.md
    // promises `{{ args.formula }}` ≡ `{{ formula }}`, and every LLM-authoring
    // example writes the `args.` form. Arguments/values land in the context flat
    // (keyed by bare name), so strip a leading `args.` before resolving — unless
    // a workflow genuinely put an `args` object in context, in which case honor
    // that literal. Without this, workflows written straight from the guide fail
    // their first render with "unknown workflow context path".
    let path = if path.starts_with("args.") && !context.contains_key("args") {
        path.strip_prefix("args.").unwrap_or(path)
    } else {
        path
    };
    let mut current = context
        .get(path.split('.').next().unwrap_or_default())
        .cloned()
        .ok_or_else(|| anyhow!("unknown workflow context path: {path}"))?;
    for segment in path.split('.').skip(1) {
        current = match current {
            serde_json::Value::Object(map) => map
                .get(segment)
                .cloned()
                .ok_or_else(|| anyhow!("unknown workflow context path: {path}"))?,
            _ => bail!("unknown workflow context path: {path}"),
        };
    }
    Ok(current)
}

/// SSRF guard for workflow `http` steps. Returns `Some(reason)` when
/// the URL must be rejected, `None` when it's acceptable.
///
/// Blocks:
///   - non-http(s) schemes (file://, gopher://, dict://, data://, …)
///   - empty / unparseable URLs
///   - hostnames that resolve to local / metadata-service contexts:
///     `localhost`, `0.0.0.0`, RFC1918 / loopback / link-local literals,
///     and the well-known cloud metadata service IP `169.254.169.254`
///   - common metadata hostnames: `metadata`, `metadata.google.internal`
///
/// What this does NOT do (and why a future allowlist is the right
/// long-term fix): defend against DNS rebinding (resolves to a public
/// IP at parse time, then to an internal IP at request time), or any
/// host that an attacker controls and points at internal infra. Users
/// running marketplace workflows against sensitive networks should add
/// a hostname allowlist to their workflow runtime config.
fn ssrf_block_reason(url: &str) -> Option<&'static str> {
    // reqwest::Url is the same `url::Url` from the url crate; using it
    // via reqwest avoids adding a top-level dependency just for parse.
    let Ok(parsed) = reqwest::Url::parse(url) else {
        return Some("URL did not parse");
    };

    // 1. Scheme: only http(s).
    match parsed.scheme() {
        "http" | "https" => {}
        _ => return Some("only http(s) URLs are allowed"),
    }

    let Some(host) = parsed.host_str() else {
        return Some("URL has no host");
    };
    let host = host.to_ascii_lowercase();

    // 2. Literal hostnames that name local / metadata contexts.
    const BLOCKED_HOSTS: &[&str] = &[
        "localhost",
        "ip6-localhost",
        "ip6-loopback",
        "metadata",
        "metadata.google.internal",
    ];
    if BLOCKED_HOSTS.contains(&host.as_str()) {
        return Some("hostname names a loopback or cloud-metadata service");
    }

    // 3. Reject literal IPs that fall into private / loopback / link-local
    // ranges. We don't do DNS lookup here — DNS rebinding still works.
    // The literal-IP check stops the obvious SSRF payloads.
    if let Ok(ipv4) = host.parse::<std::net::Ipv4Addr>() {
        if ipv4.is_loopback()
            || ipv4.is_private()
            || ipv4.is_link_local()
            || ipv4.is_unspecified()
            || ipv4.is_broadcast()
        {
            return Some("IPv4 address is in a private / loopback / link-local range");
        }
        // 169.254.169.254 is link-local but call it out specifically.
        if ipv4.octets() == [169, 254, 169, 254] {
            return Some("address is the cloud instance metadata service");
        }
    }
    // url crate strips the [] from IPv6 hosts, but the host_str() form
    // returns it WITH the brackets. Strip them before parsing.
    let ipv6_candidate = host
        .strip_prefix('[')
        .and_then(|s| s.strip_suffix(']'))
        .unwrap_or(host.as_str());
    if let Ok(ipv6) = ipv6_candidate.parse::<std::net::Ipv6Addr>()
        && (ipv6.is_loopback() || ipv6.is_unspecified())
    {
        return Some("IPv6 address is loopback / unspecified");
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_builtin_forge() {
        let specs = discover_workflows(None).unwrap();
        let forge = find_workflow(&specs, "forge").unwrap();
        assert_eq!(forge.command_name, "forge");
        assert!(!forge.steps.is_empty());
    }

    #[test]
    fn parses_external_workflow_alias_args() {
        let parsed = parse_workflow_command_args(&[
            "forge".to_string(),
            "--paper".to_string(),
            "arxiv:2106.09685".to_string(),
            "--dataset".to_string(),
            "materials-project".to_string(),
            "--target".to_string(),
            "runpod:A100".to_string(),
            "--execute".to_string(),
        ])
        .unwrap();
        assert_eq!(parsed.name, "forge");
        assert!(parsed.execute);
        assert_eq!(parsed.values.get("paper").unwrap(), "arxiv:2106.09685");
    }

    #[test]
    fn dry_run_set_step_updates_context() {
        let spec = load_workflow_from_str(
            r#"
kind: workflow
name: test
command_name: test
arguments:
  - name: paper
    required: true
steps:
  - id: first
    action: set
    values:
      paper: "{{paper}}"
  - id: second
    action: message
    text: "paper={{paper}}"
"#,
            "inline:test",
        )
        .unwrap();
        let mut values = BTreeMap::new();
        values.insert("paper".to_string(), "abc".to_string());
        let result = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(execute_workflow(&spec, &values, false))
            .unwrap();
        assert_eq!(result.steps[0].status, "planned");
        assert_eq!(result.steps[1].summary, "paper=abc");
    }

    // ── Round-N robustness tests: schema accepts LLM-friendly shapes ──

    #[test]
    fn auto_generates_step_ids_when_missing() {
        // LLMs commonly omit `id:` on steps. The parser must auto-generate.
        let spec = load_workflow_from_str(
            r#"
name: auto_id_test
arguments:
  - name: x
steps:
  - action: set
    key: foo
    value: bar
  - action: message
    text: "hi"
"#,
            "inline:auto_id_test",
        )
        .unwrap();
        assert_eq!(spec.steps.len(), 2);
        // IDs include the action for readability
        assert_eq!(spec.steps[0].id, "set_0");
        assert_eq!(spec.steps[1].id, "message_1");
    }

    #[test]
    fn accepts_inputs_alias_for_arguments() {
        // skill_workflow + many LLM-generated workflows use `inputs:` at top
        // level instead of `arguments:`. Both must work.
        let spec = load_workflow_from_str(
            r#"
name: aliases_test
inputs:
  - name: query
    required: true
    description: "natural-language query"
steps:
  - action: message
    text: "got {{query}}"
"#,
            "inline:aliases_test",
        )
        .unwrap();
        assert_eq!(spec.arguments.len(), 1);
        assert_eq!(spec.arguments[0].name, "query");
        // `description:` accepted as alias for `help:`
        assert_eq!(spec.arguments[0].help, "natural-language query");
    }

    #[test]
    fn accepts_tasks_alias_for_steps() {
        // Pre-1.0 workflow files used `tasks:` instead of `steps:`.
        let spec = load_workflow_from_str(
            r#"
name: legacy_tasks_test
tasks:
  - id: a
    action: message
    text: "from a"
  - id: b
    action: message
    text: "from b"
"#,
            "inline:legacy_tasks_test",
        )
        .unwrap();
        assert_eq!(spec.steps.len(), 2);
    }

    #[test]
    fn accepts_legacy_kind_aliases() {
        // pre-1.0 used `kind: prism_workflow`.
        let spec = load_workflow_from_str(
            r#"
kind: prism_workflow
name: legacy_kind
steps:
  - action: message
    text: "hi"
"#,
            "inline:legacy_kind",
        )
        .unwrap();
        assert_eq!(spec.steps.len(), 1);
    }

    #[test]
    fn rejects_unknown_action_with_did_you_mean() {
        // LLM types `tools` instead of `tool` — should get a hint.
        let err = load_workflow_from_str(
            r#"
name: typo_test
steps:
  - action: tools
    name: web
"#,
            "inline:typo_test",
        )
        .unwrap_err()
        .to_string();
        assert!(err.contains("unknown action"), "got: {err}");
        assert!(err.contains("Did you mean `action: tool`"), "got: {err}");
    }

    #[test]
    fn rejects_unknown_action_with_valid_list_when_no_close_match() {
        // No edit-distance match → list valid actions.
        let err = load_workflow_from_str(
            r#"
name: typo_test
steps:
  - action: zzzzzz
"#,
            "inline:typo_test",
        )
        .unwrap_err()
        .to_string();
        assert!(err.contains("unknown action"), "got: {err}");
        assert!(err.contains("Valid actions:"), "got: {err}");
        assert!(err.contains("tool"), "got: {err}");
    }

    #[test]
    fn rejects_step_with_no_action() {
        let err = load_workflow_from_str(
            r#"
name: no_action_test
steps:
  - id: orphan
    name: web
"#,
            "inline:no_action",
        )
        .unwrap_err()
        .to_string();
        assert!(err.contains("no `action`"), "got: {err}");
    }

    #[test]
    fn rejects_skill_workflow_dialect_with_helpful_message() {
        let err = load_workflow_from_str(
            r#"
kind: skill_workflow
name: skill_test
inputs:
  - name: q
"#,
            "inline:skill_test",
        )
        .unwrap_err()
        .to_string();
        assert!(
            err.contains("skill_workflow") || err.contains("dialect"),
            "got: {err}"
        );
    }

    #[test]
    fn edit_distance_basic() {
        assert_eq!(edit_distance("tool", "tool"), 0);
        assert_eq!(edit_distance("tools", "tool"), 1);
        assert_eq!(edit_distance("tols", "tool"), 2);
        assert_eq!(edit_distance("", "abc"), 3);
        assert_eq!(edit_distance("abc", ""), 3);
    }

    #[test]
    fn suggest_action_finds_close_match() {
        assert_eq!(suggest_action("tools"), Some("tool"));
        assert_eq!(suggest_action("messag"), Some("message"));
        assert_eq!(suggest_action("paralel"), Some("parallel"));
        assert_eq!(suggest_action("Workflow"), Some("workflow"));
        // No close match → None
        assert_eq!(suggest_action("xxxxxxxxxxxxx"), None);
    }

    // ── Step-level field-alias tests ──────────────────────────────────
    //
    // Each test parses + dry-runs a workflow that uses LLM-friendly
    // alternative field names instead of the canonical ones. The
    // canonical names are still the ones documented; aliases just
    // reduce friction when an LLM emits its best-guess YAML.

    fn dry_run(yaml: &str) -> WorkflowRunResult {
        let spec = load_workflow_from_str(yaml, "inline:test").unwrap();
        let values = BTreeMap::new();
        tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(execute_workflow(&spec, &values, false))
            .unwrap()
    }

    #[test]
    fn set_step_accepts_vars_alias_for_values() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: s
    action: set
    vars:
      hello: world
"#,
        );
        assert_eq!(result.steps[0].status, "planned");
        // The step result should record the value(s) under vars
        let data = &result.steps[0].data;
        assert_eq!(data["values"]["hello"], "world");
    }

    #[test]
    fn set_step_accepts_data_alias_for_values() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: s
    action: set
    data:
      n: 42
"#,
        );
        assert_eq!(result.steps[0].data["values"]["n"], 42);
    }

    #[test]
    fn message_step_accepts_body_alias_for_text() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: m
    action: message
    body: "hello via body"
"#,
        );
        assert_eq!(result.steps[0].summary, "hello via body");
    }

    #[test]
    fn message_step_accepts_content_alias_for_text() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: m
    action: message
    content: "hello via content"
"#,
        );
        assert_eq!(result.steps[0].summary, "hello via content");
    }

    #[test]
    fn tool_step_accepts_tool_alias_for_name() {
        // dry_run never hits the network — we only verify parse + plan.
        let result = dry_run(
            r#"
name: t
steps:
  - id: call
    action: tool
    tool: web
    cmd: search
    args:
      q: "hello"
"#,
        );
        assert_eq!(result.steps[0].status, "planned");
        // Summary format: "tool:<name> <command>"
        let summary = &result.steps[0].summary;
        assert!(summary.contains("tool:web"), "summary: {summary}");
        // The dry-run data echoes the resolved name + inputs
        assert_eq!(result.steps[0].data["tool"], "web");
        assert_eq!(result.steps[0].data["command"], "search");
        assert_eq!(result.steps[0].data["inputs"]["q"], "hello");
    }

    #[test]
    fn tool_step_accepts_with_alias_for_inputs() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: call
    action: tool
    name: ml
    with:
      target: hardness
"#,
        );
        assert_eq!(result.steps[0].data["inputs"]["target"], "hardness");
    }

    #[test]
    fn if_step_accepts_when_alias_for_condition() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: gate
    action: if
    when: "true"
    then:
      - id: yes
        action: message
        text: "branch taken"
    else:
      - id: no
        action: message
        text: "skipped"
"#,
        );
        // Truthy "true" string → then branch
        let summary = &result.steps[0].summary;
        assert!(summary.contains("then"), "summary: {summary}");
    }

    #[test]
    fn parallel_step_accepts_tasks_alias_for_steps() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: fanout
    action: parallel
    tasks:
      - id: a
        action: message
        text: "first"
      - id: b
        action: message
        text: "second"
"#,
        );
        assert_eq!(result.steps[0].status, "planned");
        // The dry-run path records step_count under data
        assert_eq!(result.steps[0].data["step_count"], 2);
    }

    #[test]
    fn workflow_step_accepts_workflow_alias_for_name() {
        // dry-run doesn't actually invoke the sub-workflow, so it's
        // safe to point at a name that won't resolve.
        let result = dry_run(
            r#"
name: parent
steps:
  - id: invoke
    action: workflow
    workflow: child_wf
    args:
      x: 1
"#,
        );
        assert_eq!(result.steps[0].status, "planned");
        assert_eq!(result.steps[0].data["workflow"], "child_wf");
        assert_eq!(result.steps[0].data["inputs"]["x"], 1);
    }

    #[test]
    fn step_aliases_are_llm_friendly_combo() {
        // Stack as many aliases as a hypothetical LLM would emit, then
        // verify the workflow still parses + dry-runs cleanly.
        let result = dry_run(
            r#"
kind: prism_workflow
name: combo
inputs:
  - name: q
    description: "the query"
tasks:
  - action: set
    data:
      query: "{{q}}"
  - action: message
    body: "running with {{query}}"
  - action: tool
    tool: web
    cmd: search
    with:
      q: "{{query}}"
  - action: if
    when: "true"
    then:
      - id: ok
        action: message
        text: "good"
  - action: parallel
    tasks:
      - id: a
        action: message
        text: "left"
      - id: b
        action: message
        text: "right"
"#,
        );
        assert_eq!(result.steps.len(), 5);
        // All five auto-generated step IDs use the action prefix
        assert_eq!(result.steps[0].id, "set_0");
        assert_eq!(result.steps[1].id, "message_1");
        assert_eq!(result.steps[2].id, "tool_2");
        assert_eq!(result.steps[3].id, "if_3");
        assert_eq!(result.steps[4].id, "parallel_4");
    }

    // ── SSRF guard tests (Bug #56) ──────────────────────────────────

    #[test]
    fn ssrf_allows_public_https_urls() {
        assert!(ssrf_block_reason("https://api.materialsproject.org/").is_none());
        assert!(ssrf_block_reason("https://optimade.org/v1/structures").is_none());
        assert!(ssrf_block_reason("http://example.com:8080/path").is_none());
    }

    #[test]
    fn ssrf_blocks_localhost() {
        assert!(ssrf_block_reason("http://localhost:7327/api/users").is_some());
        assert!(ssrf_block_reason("http://127.0.0.1/").is_some());
        assert!(ssrf_block_reason("http://127.255.255.254/").is_some());
        assert!(ssrf_block_reason("http://[::1]/").is_some());
    }

    #[test]
    fn ssrf_blocks_private_ipv4() {
        assert!(ssrf_block_reason("http://10.0.0.1/").is_some());
        assert!(ssrf_block_reason("http://172.16.0.1/").is_some());
        assert!(ssrf_block_reason("http://192.168.1.1/admin").is_some());
        assert!(ssrf_block_reason("http://0.0.0.0/").is_some());
    }

    #[test]
    fn ssrf_blocks_link_local_and_metadata() {
        assert!(ssrf_block_reason("http://169.254.0.1/").is_some());
        assert!(ssrf_block_reason("http://169.254.169.254/latest/meta-data/").is_some());
        assert!(ssrf_block_reason("http://metadata.google.internal/").is_some());
        assert!(ssrf_block_reason("http://metadata/").is_some());
    }

    #[test]
    fn ssrf_blocks_dangerous_schemes() {
        assert!(ssrf_block_reason("file:///etc/passwd").is_some());
        assert!(ssrf_block_reason("gopher://internal:1337/").is_some());
        assert!(ssrf_block_reason("dict://attacker.com:1337/").is_some());
        assert!(ssrf_block_reason("data:text/plain,foo").is_some());
        assert!(ssrf_block_reason("ftp://internal/").is_some());
    }

    #[test]
    fn ssrf_blocks_unparseable_urls() {
        assert!(ssrf_block_reason("not a url").is_some());
        assert!(ssrf_block_reason("").is_some());
    }

    // ── llm step tests ──────────────────────────────────────────────

    #[test]
    fn llm_step_dry_run_plans_without_calling_llm() {
        let yaml = r#"
name: llm-dry-run
description: test
command_name: llm-dry-run
arguments:
  - name: material
    type: string
    required: true
steps:
  - id: reason
    action: llm
    prompt: "What is {{ material }}?"
    system: "You are a scientist."
    output_key: answer
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        let rt = tokio::runtime::Runtime::new().unwrap();
        let mut values = BTreeMap::new();
        values.insert("material".to_string(), "TiAl".to_string());
        let result = rt
            .block_on(execute_workflow(&spec, &values, false))
            .unwrap();
        assert_eq!(result.steps.len(), 1);
        assert_eq!(result.steps[0].status, "planned");
        assert!(result.steps[0].summary.contains("llm prompt"));
    }

    #[test]
    fn llm_step_parses_with_all_options() {
        let yaml = r#"
name: llm-full
description: test
command_name: llm-full
steps:
  - id: reason
    action: llm
    prompt: "Analyze {{ data }}"
    system: "You are a materials scientist."
    model: "gemma-4-12b"
    temperature: 0.5
    max_tokens: 1000
    output_key: analysis
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        assert_eq!(spec.steps.len(), 1);
        assert_eq!(spec.steps[0].action, "llm");
    }

    #[test]
    fn llm_step_in_known_actions() {
        assert!(KNOWN_ACTIONS.contains(&"llm"));
    }

    #[test]
    fn node_token_is_stripped_from_returned_context() {
        // The reserved `_node_token` credential — injected by the CLI/agent to
        // authenticate `tool` steps to the local node — must never leak back
        // out in the returned context, which the CLI renders and the agent
        // returns as its tool result. A single `message` step keeps this run
        // tool-free so no HTTP call is attempted.
        let yaml = r#"
name: token-strip
description: test
command_name: token-strip
steps:
  - id: note
    action: message
    text: "hello"
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        let mut values = BTreeMap::new();
        values.insert(
            "_node_token".to_string(),
            "secret-loopback-token".to_string(),
        );
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt.block_on(execute_workflow(&spec, &values, true)).unwrap();
        assert!(
            !result.context.contains_key("_node_token"),
            "injected _node_token leaked into returned context: {:?}",
            result.context.keys().collect::<Vec<_>>()
        );
    }

    // ── loop step tests ─────────────────────────────────────────────

    #[test]
    fn loop_step_dry_run_plans_iterations() {
        let yaml = r#"
name: loop-dry
description: test
command_name: loop-dry
steps:
  - id: iterate
    action: loop
    max_iterations: 5
    until: "{{ done }}"
    steps:
      - id: sample
        action: tool
        name: sample_material
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt
            .block_on(execute_workflow(&spec, &BTreeMap::new(), false))
            .unwrap();
        assert_eq!(result.steps.len(), 1);
        assert_eq!(result.steps[0].status, "planned");
        assert!(result.steps[0].summary.contains("loop"));
    }

    #[test]
    fn loop_step_parses_with_body_and_until() {
        let yaml = r#"
name: loop-test
description: test
command_name: loop-test
steps:
  - id: discover
    action: loop
    max_iterations: 10
    until: "{{ done }}"
    steps:
      - id: s1
        action: set
        values: { x: "1" }
      - id: s2
        action: set
        values: { done: "true" }
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        assert_eq!(spec.steps.len(), 1);
        assert_eq!(spec.steps[0].action, "loop");
    }

    #[test]
    fn loop_step_in_known_actions() {
        assert!(KNOWN_ACTIONS.contains(&"loop"));
    }

    #[test]
    fn loop_step_with_empty_body_errors() {
        let yaml = r#"
name: loop-empty
description: test
command_name: loop-empty
steps:
  - id: empty
    action: loop
    max_iterations: 3
    steps: []
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt.block_on(execute_workflow(&spec, &BTreeMap::new(), true));
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("no body steps"));
    }

    #[test]
    fn loop_step_executes_and_stops_on_condition() {
        let yaml = r#"
name: loop-cond
description: test
command_name: loop-cond
steps:
  - id: iterate
    action: loop
    max_iterations: 10
    until: "{{ stop }}"
    steps:
      - id: set_stop
        action: set
        values: { stop: "true" }
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt
            .block_on(execute_workflow(&spec, &BTreeMap::new(), true))
            .unwrap();
        assert_eq!(result.steps.len(), 1);
        assert_eq!(result.steps[0].status, "completed");
        // Should stop after 1 iteration because `stop` is set to "true"
        assert!(result.steps[0].summary.contains("1 iteration"));
        assert!(result.steps[0].summary.contains("until met"));
    }

    #[test]
    fn loop_step_runs_to_max_without_until() {
        let yaml = r#"
name: loop-max
description: test
command_name: loop-max
steps:
  - id: iterate
    action: loop
    max_iterations: 3
    steps:
      - id: noop
        action: set
        values: { x: "1" }
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt
            .block_on(execute_workflow(&spec, &BTreeMap::new(), true))
            .unwrap();
        assert_eq!(result.steps.len(), 1);
        assert!(result.steps[0].summary.contains("3 iteration"));
        assert!(result.steps[0].summary.contains("max reached"));
    }

    #[test]
    fn loop_step_caps_max_iterations_at_100() {
        let yaml = r#"
name: loop-cap
description: test
command_name: loop-cap
steps:
  - id: iterate
    action: loop
    max_iterations: 999
    steps:
      - id: noop
        action: set
        values: { x: "1" }
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt
            .block_on(execute_workflow(&spec, &BTreeMap::new(), false))
            .unwrap();
        // Dry-run shows the planned max (capped at 100 in the handler,
        // but dry-run summary reflects the cap)
        assert_eq!(result.steps[0].status, "planned");
    }

    // ── combined agentic pipeline test ──────────────────────────────

    #[test]
    fn agentic_pipeline_dry_run_with_llm_and_loop() {
        // A realistic materials-discovery pipeline shape.  Dry-run
        // still interpolates templates, so we only reference the input
        // arg `goal` (which is in context from the start), not outputs
        // of prior steps (which don't exist in dry-run).
        let yaml = r#"
name: discover
description: Agentic materials discovery pipeline
command_name: discover
arguments:
  - name: goal
    type: string
    required: true
    help: Materials discovery goal
steps:
  - id: reason
    action: llm
    prompt: "Propose 3 candidate compositions for {{ goal }}."
    system: "You are a materials scientist."
    output_key: candidates
  - id: discover_loop
    action: loop
    max_iterations: 5
    until: "{{ done }}"
    steps:
      - id: check
        action: set
        values: { done: "true" }
"#;
        let spec = load_workflow_from_str(yaml, "test.yaml").unwrap();
        assert_eq!(spec.steps.len(), 2);
        assert_eq!(spec.steps[0].action, "llm");
        assert_eq!(spec.steps[1].action, "loop");

        // Dry-run should plan all steps without executing anything.
        let rt = tokio::runtime::Runtime::new().unwrap();
        let mut values = BTreeMap::new();
        values.insert("goal".to_string(), "high-strength Ti alloy".to_string());
        let result = rt
            .block_on(execute_workflow(&spec, &values, false))
            .unwrap();
        assert_eq!(result.steps.len(), 2);
        for step in &result.steps {
            assert_eq!(step.status, "planned");
        }
    }

    // ── `args.` prefix convention ─────────────────────────────────────
    //
    // docs/workflows.md promises `{{ args.x }}` ≡ `{{ x }}`. Arguments land
    // in context flat, so resolve_path must strip a leading `args.`.

    #[test]
    fn resolve_path_strips_args_prefix() {
        let mut ctx = BTreeMap::new();
        ctx.insert("formula".to_string(), serde_json::json!("Ni"));
        // Both spellings resolve to the same flat value.
        assert_eq!(
            resolve_path(&ctx, "formula").unwrap(),
            serde_json::json!("Ni")
        );
        assert_eq!(
            resolve_path(&ctx, "args.formula").unwrap(),
            serde_json::json!("Ni")
        );
    }

    #[test]
    fn resolve_path_honors_literal_args_object() {
        // If a workflow genuinely has an `args` object in context, the literal
        // wins over the strip-the-prefix convention.
        let mut ctx = BTreeMap::new();
        ctx.insert("args".to_string(), serde_json::json!({ "formula": "Fe" }));
        ctx.insert("formula".to_string(), serde_json::json!("Ni"));
        assert_eq!(
            resolve_path(&ctx, "args.formula").unwrap(),
            serde_json::json!("Fe")
        );
    }

    #[test]
    fn workflow_default_arg_renders_via_args_prefix() {
        // End-to-end: an arg with a default, referenced as `{{ args.x }}`,
        // renders in dry-run (the shape every LLM-authored workflow uses).
        let result = dry_run(
            r#"
name: t
arguments:
  - name: formula
    default: "Ni"
steps:
  - id: predict
    action: tool
    name: predict
    inputs:
      formula: "{{ args.formula }}"
"#,
        );
        assert_eq!(result.steps[0].status, "planned");
        assert_eq!(result.steps[0].data["inputs"]["formula"], "Ni");
    }

    // ── approval forwarding ───────────────────────────────────────────
    //
    // Approval-gated tools (execute_python, compute_submit, …) run headless
    // only when pre-approved. `approve: true` on a tool step IS that approval
    // and must reach the node endpoint. Dry-run records it so it's visible.

    #[test]
    fn tool_step_forwards_approve_flag() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: run_py
    action: tool
    name: execute_python
    approve: true
    inputs:
      code: "print(1)"
"#,
        );
        assert_eq!(result.steps[0].data["approve"], true);
    }

    #[test]
    fn tool_step_approve_defaults_false() {
        let result = dry_run(
            r#"
name: t
steps:
  - id: search
    action: tool
    name: knowledge
    inputs:
      action: search
      term: "Ni"
"#,
        );
        assert_eq!(result.steps[0].data["approve"], false);
    }
}
